// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0Ln4lPHnuV0Iiu5TYj1V2qyAgoB3b13Y',
    appId: '1:825994411482:web:10c34e0c549ed16bdfd4e3',
    messagingSenderId: '825994411482',
    projectId: 'techify-91dc3',
    authDomain: 'techify-91dc3.firebaseapp.com',
    storageBucket: 'techify-91dc3.firebasestorage.app',
    measurementId: 'G-WEE766L3XP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL9vLy7hP4HCxMTVzGwH0HvG_9xcCyPuc',
    appId: '1:825994411482:android:911d07101cc93c1ddfd4e3',
    messagingSenderId: '825994411482',
    projectId: 'techify-91dc3',
    storageBucket: 'techify-91dc3.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0Ln4lPHnuV0Iiu5TYj1V2qyAgoB3b13Y',
    appId: '1:825994411482:web:26a00c8421947ebfdfd4e3',
    messagingSenderId: '825994411482',
    projectId: 'techify-91dc3',
    authDomain: 'techify-91dc3.firebaseapp.com',
    storageBucket: 'techify-91dc3.firebasestorage.app',
    measurementId: 'G-NK7126Z2LV',
  );

}